language: python
python:
  - "3.8"
  - "3.9"
  - "3.10"

dist: xenial  # Используем более старую, но стабильную среду

services:
  - xvfb

addons:
  apt:
    packages:
      - libgl1-mesa-glx
      - libgtk2.0-0
      - libsm6
      - libxext6
      - libxrender-dev

before_install:
  - sudo apt-get update
  - python --version
  - pip --version

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install pytest pytest-cov

script:
  # Проверяем импорты основных модулей
  - python -c "import flask; print('Flask version:', flask.__version__)"
  - python -c "import cv2; print('OpenCV version:', cv2.__version__)"
  - python -c "import numpy; print('NumPy version:', numpy.__version__)"
  - python -c "import matplotlib; print('Matplotlib version:', matplotlib.__version__)"
  - python -c "import requests; print('Requests version:', requests.__version__)"
  
  # Запускаем тесты
  - python -m pytest tests/ -v --cov=.

  # Проверяем запуск приложения
  - timeout 10s python some_app.py &
  - sleep 3
  - curl -f http://localhost:5000/ || echo "Server started successfully"

after_success:
  - echo "✅ All tests passed successfully!"
  - echo "Python version: $(python --version)"
  - echo "Build completed: $(date)"

notifications:
  email:
    on_success: never
    on_failure: always

cache:
  pip: true
  directories:
    - $HOME/.cache/pip
