language: python
python:
  - "3.8"
  - "3.9"
  - "3.10"

services:
  - xvfb

install:
  - pip install -r requirements.txt
  - pip install pytest pytest-cov

script:
  - python -c "import flask; print('Flask version:', flask.__version__)"
  - python -c "import cv2; print('OpenCV version:', cv2.__version__)"
  - python -c "import numpy; print('NumPy version:', numpy.__version__)"
  - python client.py

after_success:
  - echo "All tests passed successfully!"

notifications:
  email: false
