language: python
version: 1.0.{build}
image: Visual Studio 2022

environment:
  matrix:
    - PYTHON: "C:\\Python38"
      PYTHON_VERSION: "3.8.0"
      PYTHON_ARCH: "32"
    - PYTHON: "C:\\Python39"
      PYTHON_VERSION: "3.9.0"
      PYTHON_ARCH: "32"
    - PYTHON: "C:\\Python310"
      PYTHON_VERSION: "3.10.0"
      PYTHON_ARCH: "32"

install:
  - ECHO "Installing Python %PYTHON_VERSION%"
  - SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - python --version
  - pip --version
  - pip install -r requirements.txt
  - pip install pytest pytest-cov

build: off

test_script:
  - python -m pytest tests/ -v --cov=.
  - python run_tests.py

after_test:
  - ECHO "Tests completed successfully"

deploy: off
