name: Lab1 CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-glx libgtk2.0-0 libsm6 libxext6 libxrender-dev
    
    - name: Install Python dependencies
      run: |
        cd lab1_task/flaskapp
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    
    - name: Debug info
      run: |
        cd lab1_task/flaskapp
        echo "=== Project Structure ==="
        ls -la
        echo "=== Tests Structure ==="
        ls -la tests/ || echo "No tests directory"
        echo "=== Python Path ==="
        python -c "import sys; print('\\n'.join(sys.path))"
    
    - name: Run tests with verbose output
      run: |
        cd lab1_task/flaskapp
        python -m pytest tests/ -v -s --tb=short
    
    - name: Verify basic functionality
      run: |
        cd lab1_task/flaskapp
        python -c "
import sys
sys.path.insert(0, '.')
try:
    from some_app import app, blend_images
    print('✅ Main imports successful')
    
    # Test basic function
    import numpy as np
    img1 = np.ones((10, 10, 3), dtype=np.uint8) * 255
    img2 = np.zeros((10, 10, 3), dtype=np.uint8)
    result = blend_images(img1, img2, 0.5)
    print('✅ Basic functionality test passed')
    
except Exception as e:
    print(f'❌ Error: {e}')
    import traceback
    traceback.print_exc()
    exit(1)
        "
