name: Lab1 Flask App CI

on:
  push:
    branches: [ main ]
    paths:
      - 'lab1_task/**'        # Запускать только при изменениях в lab1_task
  pull_request:
    branches: [ main ]
    paths:
      - 'lab1_task/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-glx libgtk2.0-0 libsm6 libxext6 libxrender-dev
    
    - name: Install Python dependencies
      run: |
        cd lab1_task/flaskapp
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
    
    - name: Run tests
      run: |
        cd lab1_task/flaskapp
        python -m pytest tests/ -v --cov=. --tb=short
    
    - name: Verify imports
      run: |
        cd lab1_task/flaskapp
        python -c "import flask; print('✅ Flask version:', flask.__version__)"
        python -c "import cv2; print('✅ OpenCV version:', cv2.__version__)"
        python -c "import numpy; print('✅ NumPy version:', numpy.__version__)"
        python -c "import matplotlib; print('✅ Matplotlib version:', matplotlib.__version__)"
